# Generated by Django 6.0.3 on 2026-06-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_placementsession_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementsession',
            name='session_number',
        ),
    ]
