# Generated by Django 6.0.3 on 2026-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_trainingsession_trainingquestionhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementsession',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
