# Generated by Django 6.0.3 on 2026-03-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('editor', 'Editor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
