# Generated by Django 6.0.3 on 2026-06-19 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_gender'),
        ('content', '0002_alter_concept_options_remove_concept_examples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='content.category'),
        ),
    ]
