# Generated by Django 6.0.3 on 2026-03-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
