# Generated by Django 6.0.3 on 2026-06-11 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='concept',
            name='examples',
        ),
        migrations.AddField(
            model_name='concept',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concept',
            name='placement_questions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concept',
            name='reference_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='concept',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='concept',
            name='reference_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='training_questions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placementquestion',
            name='concept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='placement_questions', to='content.concept'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placementquestion',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ConceptExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('solve', models.TextField()),
                ('explanation', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='content.concept')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True / False'), ('fill_blank', 'Fill in the Blank'), ('ordering', 'Ordering')], max_length=20)),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, default=list, help_text='للـ multiple_choice: ["خيار1", "خيار2", ...]')),
                ('correct_answer', models.TextField()),
                ('explanation', models.TextField(help_text='يظهر للطالب بعد الإجابة دائماً')),
                ('hint', models.CharField(blank=True, help_text='يظهر عند طلب الطالب تلميحاً', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_questions', to='content.concept')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
