# Generated by Django 6.0.3 on 2026-07-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_concept_options_remove_concept_examples_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='level',
        ),
        migrations.AddField(
            model_name='trainingquestion',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.DeleteModel(
            name='ConceptExample',
        ),
    ]
