# Generated by Django 6.0.3 on 2026-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_concept_level_trainingquestion_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/categories/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/subjects/'),
        ),
    ]
