# Generated by Django 6.0.3 on 2026-08-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_channel_channelmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
