# Generated by Django 6.0.3 on 2026-08-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_channel_updated_at_channelmessage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/placement/'),
        ),
        migrations.AddField(
            model_name='trainingquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/training/'),
        ),
    ]
