# Generated by Django 6.0.3 on 2026-08-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_placementquestion_image_trainingquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='placement_num_concepts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='skill',
            name='placement_total_questions',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
