# Generated by Django 6.0.3 on 2026-08-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_skill_placement_num_concepts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='created_by',
        ),
    ]
