# Generated by Django 6.0.3 on 2026-08-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_skill_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingquestion',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='للـ multiple_choice: ["خيار1", "خيار2", ...]', null=True),
        ),
    ]
