# Generated by Django 6.0.3 on 2026-08-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_trainingquestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='training_advanced_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='skill',
            name='training_beginner_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='skill',
            name='training_intermediate_count',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
