# Generated by Django 6.0.3 on 2026-08-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_skill_training_advanced_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementquestion',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='For multiple_choice: ["option1", "option2", ...]', null=True),
        ),
    ]
