# Generated by Django 6.0.3 on 2026-09-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_placementquestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingquestion',
            name='explanation',
            field=models.TextField(help_text='Always shown to the student after answering'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='hint',
            field=models.CharField(blank=True, help_text='Shown when the student requests a hint', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='For multiple_choice: ["option1", "option2", ...]', null=True),
        ),
    ]
